os: "linux"

lenguage: python

dist: "xenial"
python: "3.7"

install:
  - pip install pipenv
  - pipenv install

script: pipenv run pelican -s publishconf.py -t default content

deploy:
  provider: pages
  strategy: git
  repo: pangolp/pangolp.github.io
  target_branch: gh-page
  local_dir: output
  token: $TOKEN
  edge: true
  on:
    branch: master
